[programs.localnet]
quotes_gif_program = "4H8RWS5zZsj34WitF4JEuVLUxmsQgYBA9XxWBQBT52Sz"

[programs.devnet]
quotes_gif_program = "4H8RWS5zZsj34WitF4JEuVLUxmsQgYBA9XxWBQBT52Sz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/pierre/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
